version: "3.9"

services:
  database:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=takehome_ws_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  loader:
    build: ./etl_data
    depends_on:
      database:
        condition: service_healthy
    command: bash -c "python /etl_data/create_table_and_load_data_from_csv.py /etl_data/csv_folder/${CSV_FILE_NAME}"
    volumes:
      - ./etl_data:/etl_data
      - ${PATH_TO_CSV_FOLDER}:/etl_data/csv_folder

  web-service:
    depends_on:
      database:
        condition: service_healthy
    build: .
    restart: always
    command: bash -c "
      python manage.py migrate land_temperatures --fake && python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./ws_data:/ws_data

networks:
    default:
      external:
        name: external-network
